version: "3.9"

services:
  nextapp:
    build:
      context: ./p-f-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
       - ./p-f-client:/app
       - /app/node_modules
    depends_on:
      - postgres
      - nodeapp
    environment:
      - API_END_POINT=http://nodeapp:8082 
    restart: always  
    networks:
      - next-node

  nodeapp:
    build:
      context: ./p-f-server
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./p-f-server:/app
      -  /app/node_modules
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
    networks:
      - node-postgres
      - next-node

  postgres:
    image: postgres:12-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma
    deploy:
      resources:
        limits:
          memory: 256M  # Adjust as needed
        reservations:
          memory: 256M # Adjust as needed
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - node-postgres

networks:
  next-node:
  node-postgres:

volumes:
  pgdata: